// GENERATED by scripts/pack_sprites.py -- do not edit by hand.
// Measured from the PNGs in public/sprites/; re-run the script after changing art.
import type { SpriteSheet } from './types.ts';

export type SpriteId = 'aethis' | 'backdrop_bat' | 'benjamin' | 'false_lead' | 'footlight_skitter' | 'kael' | 'maxine' | 'playbill_mimic' | 'rebar' | 'understudy_blue' | 'understudy_green' | 'understudy_orange' | 'understudy_red' | 'understudy_yellow';

export interface SpriteMetrics extends Omit<SpriteSheet, 'scale' | 'nativePx'> {
  /**
   * Figure height on the native grid it was drawn on, and the size of that grid.
   *
   * Their RATIO is the character's stature, and content.ts turns it into tiles
   * with one global factor rather than a hand-tuned table. The canvas travels
   * alongside because the guide changed it from 64 to 128: measured against a
   * fixed 64, the newer art would render at twice everyone else's height.
   *
   * Deliberately independent of which file supplies the PIXELS: size comes from
   * the native grid, quality from the best available render. `nativePx` is null
   * for pre-guide art with no native basis.
   */
  nativePx: number | null;
  nativeCanvas: number;
  /** True when the shipped sheet is native-grid art needing nearest-neighbour. */
  pixelArt: boolean;
  /**
   * Packed idle strip, when the character has one. Every frame shares one crop
   * box so only the intended parts move, and the renderer steps through it.
   */
  idle?: { src: string; frames: number; aspect: number; pxH: number; anchorX: number; restFill: number; footPad: number };
}

export const SPRITE_METRICS: Record<SpriteId, SpriteMetrics> = {
  aethis: { src: '/sprites/aethis/aethis.png', icon: '/sprites/aethis/aethis_icon.png', aspect: 70 / 97, pxH: 97, anchorX: 0.436, nativePx: 97, nativeCanvas: 128, pixelArt: true, idle: { src: '/sprites/aethis/aethis_idle.png', frames: 8, aspect: 0.707071, pxH: 99, anchorX: 0.436, restFill: 0.984848, footPad: 0.0 } },
  backdrop_bat: { src: '/sprites/backdrop_bat/backdrop_bat.png', icon: '/sprites/backdrop_bat/backdrop_bat_icon.png', aspect: 114 / 92, pxH: 92, anchorX: 0.346, nativePx: 92, nativeCanvas: 128, pixelArt: true },
  benjamin: { src: '/sprites/benjamin/benjamin.png', icon: '/sprites/benjamin/benjamin_icon.png', aspect: 103 / 85, pxH: 85, anchorX: 0.447, nativePx: 85, nativeCanvas: 128, pixelArt: true, idle: { src: '/sprites/benjamin/benjamin_idle.png', frames: 8, aspect: 1.352941, pxH: 85, anchorX: 0.496, restFill: 0.988235, footPad: 0.0 } },
  false_lead: { src: '/sprites/false_lead/false_lead.png', icon: '/sprites/false_lead/false_lead_icon.png', aspect: 226 / 203, pxH: 203, anchorX: 0.533, nativePx: 203, nativeCanvas: 128, pixelArt: true },
  footlight_skitter: { src: '/sprites/footlight_skitter/footlight_skitter.png', icon: '/sprites/footlight_skitter/footlight_skitter_icon.png', aspect: 114 / 85, pxH: 85, anchorX: 0.509, nativePx: 85, nativeCanvas: 128, pixelArt: true },
  kael: { src: '/sprites/kael/kael.png', icon: '/sprites/kael/kael_icon.png', aspect: 113 / 92, pxH: 92, anchorX: 0.478, nativePx: 92, nativeCanvas: 128, pixelArt: true, idle: { src: '/sprites/kael/kael_idle.png', frames: 8, aspect: 1.212766, pxH: 94, anchorX: 0.482, restFill: 0.984043, footPad: 0.0 } },
  maxine: { src: '/sprites/maxine/maxine.png', icon: '/sprites/maxine/maxine_icon.png', aspect: 83 / 108, pxH: 108, anchorX: 0.602, nativePx: 108, nativeCanvas: 128, pixelArt: true, idle: { src: '/sprites/maxine/maxine_idle.png', frames: 8, aspect: 0.831776, pxH: 107, anchorX: 0.545, restFill: 0.953271, footPad: 0.0 } },
  playbill_mimic: { src: '/sprites/playbill_mimic/playbill_mimic.png', icon: '/sprites/playbill_mimic/playbill_mimic_icon.png', aspect: 90 / 87, pxH: 87, anchorX: 0.517, nativePx: 87, nativeCanvas: 128, pixelArt: true },
  rebar: { src: '/sprites/rebar/rebar.png', icon: '/sprites/rebar/rebar_icon.png', aspect: 106 / 82, pxH: 82, anchorX: 0.500, nativePx: 82, nativeCanvas: 128, pixelArt: true, idle: { src: '/sprites/rebar/rebar_idle.png', frames: 5, aspect: 1.247059, pxH: 85, anchorX: 0.5, restFill: 0.964706, footPad: 0.0 } },
  understudy_blue: { src: '/sprites/understudy_blue/understudy_blue.png', icon: '/sprites/understudy_blue/understudy_blue_icon.png', aspect: 90 / 93, pxH: 93, anchorX: 0.367, nativePx: 93, nativeCanvas: 128, pixelArt: true },
  understudy_green: { src: '/sprites/understudy_green/understudy_green.png', icon: '/sprites/understudy_green/understudy_green_icon.png', aspect: 91 / 94, pxH: 94, anchorX: 0.368, nativePx: 94, nativeCanvas: 128, pixelArt: true },
  understudy_orange: { src: '/sprites/understudy_orange/understudy_orange.png', icon: '/sprites/understudy_orange/understudy_orange_icon.png', aspect: 90 / 95, pxH: 95, anchorX: 0.367, nativePx: 95, nativeCanvas: 128, pixelArt: true },
  understudy_red: { src: '/sprites/understudy_red/understudy_red.png', icon: '/sprites/understudy_red/understudy_red_icon.png', aspect: 92 / 95, pxH: 95, anchorX: 0.364, nativePx: 95, nativeCanvas: 128, pixelArt: true },
  understudy_yellow: { src: '/sprites/understudy_yellow/understudy_yellow.png', icon: '/sprites/understudy_yellow/understudy_yellow_icon.png', aspect: 91 / 95, pxH: 95, anchorX: 0.363, nativePx: 95, nativeCanvas: 128, pixelArt: true },
};

/** Every packed clip, for the dev animation lab. Battle uses `idle` above. */
export const ANIMATION_CLIPS: Record<string, Record<string, AnimationClip>> = {
  "aethis": {
    "idle": {
      "anchorX": 0.436,
      "aspect": 0.707071,
      "footPad": 0.0,
      "frames": 8,
      "loops": true,
      "normalised": 1.0,
      "pxH": 99,
      "restFill": 0.984848,
      "src": "/sprites/aethis/aethis_idle.png"
    }
  },
  "benjamin": {
    "idle": {
      "anchorX": 0.496,
      "aspect": 1.352941,
      "footPad": 0.0,
      "frames": 8,
      "loops": true,
      "normalised": 1.0,
      "pxH": 85,
      "restFill": 0.988235,
      "src": "/sprites/benjamin/benjamin_idle.png"
    }
  },
  "kael": {
    "idle": {
      "anchorX": 0.482,
      "aspect": 1.212766,
      "footPad": 0.0,
      "frames": 8,
      "loops": true,
      "normalised": 1.0,
      "pxH": 94,
      "restFill": 0.984043,
      "src": "/sprites/kael/kael_idle.png"
    }
  },
  "maxine": {
    "idle": {
      "anchorX": 0.545,
      "aspect": 0.831776,
      "footPad": 0.0,
      "frames": 8,
      "loops": true,
      "normalised": 1.0,
      "pxH": 107,
      "restFill": 0.953271,
      "src": "/sprites/maxine/maxine_idle.png"
    }
  },
  "rebar": {
    "idle": {
      "anchorX": 0.5,
      "aspect": 1.247059,
      "footPad": 0.0,
      "frames": 5,
      "loops": true,
      "normalised": 1.0,
      "pxH": 85,
      "restFill": 0.964706,
      "src": "/sprites/rebar/rebar_idle.png"
    }
  }
};

export interface AnimationClip {
  src: string;
  frames: number;
  aspect: number;
  /** The strip's own height in file pixels, for rounding to whole art pixels. */
  pxH: number;
  anchorX: number;
  /**
   * How much of the box height the RESTING figure occupies (its MEDIAN frame,
   * so a bounce apex does not read as height), and how far its feet sit above
   * the box bottom. Both 0-1.
   *
   * The box is the union of every clip a character owns, so it is as tall as
   * the highest jump and as wide as the widest swing -- it is not the
   * character. Sizing a clip by its box height therefore drew the figure
   * smaller than the same character's tight-cropped still, and by an amount
   * that changed whenever a new clip was added. Divide the intended figure
   * height by `restFill` to get the box height, then push the box down by
   * `footPad` of that to land the feet on the ground line.
   */
  restFill: number;
  footPad: number;
  /**
   * Scale the pack step applied to bring this clip in line with the reference
   * idle. 1 means the sheet was already in step. A large number means the art
   * itself disagrees and was resampled to compensate -- re-exporting the sheet
   * at a matching scale beats resampling.
   */
  normalised: number;
  /**
   * Whether the clip returns to where it started. Idles do and are trimmed to
   * whole cycles; a one-shot like a celebration ends somewhere else and plays
   * once before handing back to the idle.
   */
  loops: boolean;
  /**
   * Which clip takes over when this one finishes, for clips that do not loop.
   * A one-shot prefers its OWN held pose (`celebration` -> `celebration_ending`)
   * so a Performer keeps the stance they ended on, and falls back to `idle`.
   */
  settlesInto?: string;
}
