// GENERATED by scripts/pack_sprites.py -- do not edit by hand.
// Measured from the PNGs in public/sprites/; re-run the script after changing art.
import type { SpriteSheet } from './types.ts';

export type SpriteId = 'aethis' | 'benjamin' | 'kael' | 'maxine' | 'rebar';

export interface SpriteMetrics extends Omit<SpriteSheet, 'scale' | 'nativePx'> {
  /**
   * Figure height on the native grid it was drawn on, and the size of that grid.
   *
   * Their RATIO is the character's stature, and content.ts turns it into tiles
   * with one global factor rather than a hand-tuned table. The canvas travels
   * alongside because the guide changed it from 64 to 128: measured against a
   * fixed 64, the newer art would render at twice everyone else's height.
   *
   * Deliberately independent of which file supplies the PIXELS: size comes from
   * the native grid, quality from the best available render. `nativePx` is null
   * for pre-guide art with no native basis.
   */
  nativePx: number | null;
  nativeCanvas: number;
  /** True when the shipped sheet is native-grid art needing nearest-neighbour. */
  pixelArt: boolean;
  /**
   * Packed idle strip, when the character has one. Every frame shares one crop
   * box so only the intended parts move, and the renderer steps through it.
   */
  idle?: { src: string; frames: number; aspect: number; pxH: number; anchorX: number; restFill: number; footPad: number };
}

export const SPRITE_METRICS: Record<SpriteId, SpriteMetrics> = {
  aethis: { src: '/sprites/aethis/aethis.png', icon: '/sprites/aethis/aethis_icon.png', aspect: 236 / 320, pxH: 320, anchorX: 0.409, nativePx: 43, nativeCanvas: 64, pixelArt: false },
  benjamin: { src: '/sprites/benjamin/benjamin.png', icon: '/sprites/benjamin/benjamin_icon.png', aspect: 103 / 85, pxH: 85, anchorX: 0.447, nativePx: 85, nativeCanvas: 128, pixelArt: true, idle: { src: '/sprites/benjamin/benjamin_idle.png', frames: 8, aspect: 1.352941, pxH: 85, anchorX: 0.496, restFill: 0.988235, footPad: 0.0 } },
  kael: { src: '/sprites/kael/kael.png', icon: '/sprites/kael/kael_icon.png', aspect: 446 / 320, pxH: 320, anchorX: 0.430, nativePx: 42, nativeCanvas: 64, pixelArt: false },
  maxine: { src: '/sprites/maxine/maxine.png', icon: '/sprites/maxine/maxine_icon.png', aspect: 83 / 108, pxH: 108, anchorX: 0.602, nativePx: 108, nativeCanvas: 128, pixelArt: true, idle: { src: '/sprites/maxine/maxine_idle.png', frames: 8, aspect: 0.831776, pxH: 107, anchorX: 0.545, restFill: 0.953271, footPad: 0.0 } },
  rebar: { src: '/sprites/rebar/rebar.png', icon: '/sprites/rebar/rebar_icon.png', aspect: 403 / 320, pxH: 320, anchorX: 0.500, nativePx: 37, nativeCanvas: 64, pixelArt: false },
};

/** Every packed clip, for the dev animation lab. Battle uses `idle` above. */
export const ANIMATION_CLIPS: Record<string, Record<string, AnimationClip>> = {
  "benjamin": {
    "idle": {
      "anchorX": 0.496,
      "aspect": 1.352941,
      "footPad": 0.0,
      "frames": 8,
      "loops": true,
      "normalised": 1.0,
      "pxH": 85,
      "restFill": 0.988235,
      "src": "/sprites/benjamin/benjamin_idle.png"
    }
  },
  "maxine": {
    "idle": {
      "anchorX": 0.545,
      "aspect": 0.831776,
      "footPad": 0.0,
      "frames": 8,
      "loops": true,
      "normalised": 1.0,
      "pxH": 107,
      "restFill": 0.953271,
      "src": "/sprites/maxine/maxine_idle.png"
    }
  }
};

export interface AnimationClip {
  src: string;
  frames: number;
  aspect: number;
  /** The strip's own height in file pixels, for rounding to whole art pixels. */
  pxH: number;
  anchorX: number;
  /**
   * How much of the box height the RESTING figure occupies (its MEDIAN frame,
   * so a bounce apex does not read as height), and how far its feet sit above
   * the box bottom. Both 0-1.
   *
   * The box is the union of every clip a character owns, so it is as tall as
   * the highest jump and as wide as the widest swing -- it is not the
   * character. Sizing a clip by its box height therefore drew the figure
   * smaller than the same character's tight-cropped still, and by an amount
   * that changed whenever a new clip was added. Divide the intended figure
   * height by `restFill` to get the box height, then push the box down by
   * `footPad` of that to land the feet on the ground line.
   */
  restFill: number;
  footPad: number;
  /**
   * Scale the pack step applied to bring this clip in line with the reference
   * idle. 1 means the sheet was already in step. A large number means the art
   * itself disagrees and was resampled to compensate -- re-exporting the sheet
   * at a matching scale beats resampling.
   */
  normalised: number;
  /**
   * Whether the clip returns to where it started. Idles do and are trimmed to
   * whole cycles; a one-shot like a celebration ends somewhere else and plays
   * once before handing back to the idle.
   */
  loops: boolean;
  /**
   * Which clip takes over when this one finishes, for clips that do not loop.
   * A one-shot prefers its OWN held pose (`celebration` -> `celebration_ending`)
   * so a Performer keeps the stance they ended on, and falls back to `idle`.
   */
  settlesInto?: string;
}
